### PR TITLE
Move useNearest from Drawable to Skin

### LINKED ISSUE #565: Pen lines appear dashed in small stage mode
### Expected Behavior

Pen lines should never appear "dashed" or broken-up.

### Actual Behavior

In small-stage mode and "smallish-stage mode" (which occurs when the browser window is too small to fit a normal-sized stage), pen lines appear dashed and especially jagged, and some segments go missing:
image
image

This is a consequence of the nearest-neighbor texture filtering applied to the `PenSkin`, which downscales textures by simply removing some rows and columns of pixels, instead of blending them with neighboring pixels as linear texture filtering does.

### Steps to Reproduce

1. Enter small-stage mode (or enter "smallish-stage mode" by resizing your browser window until the stage shrinks slightly)
2. Draw some pen lines at pen size 1
3. Observe the lines' appearance

### Operating System and Browser

All

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves #565 

### Proposed Changes

This PR moves the `useNearest` method from the `Drawable` class to the `Skin` class. The default behavior is to always use nearest-neighbor interpolation, but `Skin` subclasses can override the method to provide their own behavior, and two currently do:
- `SVGSkin.useNearest` has absorbed the complex logic previously present in `Drawable.useNearest` (checking if certain effects are set, the sprite is rotated, and the scale is close to 100%).
- `PenSkin.useNearest` will use nearest-neighbor interpolation when being scaled up, and linear interpolation when being scaled down. This prevents pen lines from appearing "dashed" when a `PenSkin` is displayed at <100% scale.

### Reason for Changes

I believe this is the clearest way to implement the desired interpolation behavior for `PenSkin`s.

Since textures belong to a `Skin`, it makes sense that deciding the proper way to interpolate a texture should be the responsibility of that `Skin`.

### CODE REVIEW

**Comment by fsih** [comment]
Could you resolve conflicts?

**Comment by adroitwhiz** [comment]
Rebased to latest develop

File: src/SVGSkin.js [hunk 1]
```diff
@@ -58,6 +59,33 @@ class SVGSkin extends Skin {
         return this._svgRenderer.size;
     }
 
+    // Because SVG skins' bounding boxes are currently not pixel-aligned, the idea here is to hide blurriness
```
Comment (fsih) [inline src/SVGSkin.js]: Move this comment down t line 80?

File: src/SVGSkin.js [hunk 2]
```diff
@@ -58,6 +59,33 @@ class SVGSkin extends Skin {
...
+            return false;
+        }
+
+        // We can't use nearest neighbor unless we are a multiple of 90 rotation
+        if (this._direction % 90 !== 0) {
+            return false;
+        }
+
+        // If the scale of the skin is very close to 100 (0.99999 variance is okay I guess)
+        // TODO: Make this check more precise. Mipmaps complicate this somewhat.
```
Comment (fsih) [inline src/SVGSkin.js]: Clarify this TODO in case someone else has to implement it

**Review by fsih — DISMISSED** [review]
LGTM!

**Comment by adroitwhiz** [comment]
For some reason this is making vector sprites look blurry

**Comment by fsih** [comment]
Sorry this fell off our radar :/
It looks like there's a somewhat tricky conflict here, do you mind resolving it?

File: src/SVGSkin.js [hunk 3]
```diff
@@ -58,6 +59,35 @@ class SVGSkin extends Skin {
...
+            ShaderManager.EFFECT_INFO.pixelate.mask |
+            ShaderManager.EFFECT_INFO.mosaic.mask
+        )) !== 0) {
+            return false;
+        }
+
+        // We can't use nearest neighbor unless we are a multiple of 90 rotation
+        if (drawable._direction % 90 !== 0) {
+            return false;
+        }
```
Comment (fsih) [inline src/SVGSkin.js:76]: What do you think of keeping the drawable.useNearest function, having these lines stay there, and then having it return skin.useNearest? Then both drawable and skin get to have a say in whether we useNearest

Comment (adroitwhiz) [reply src/SVGSkin.js:76]: These lines are very `SVGSkin`-specific--it kinda sucks that `SVGSkin` depends on its parent drawable to know whether it should use nearest-neighbor interpolation but I'm not sure what else can be done.

**Review by cwillisf — APPROVED** [review]
👍 thanks!

There are some weird things going on here -- such as https://github.com/LLK/scratch-render/pull/566/files#r510419973 -- but after some thinking and discussing I think I agree that the weirdness is sort of inherent to the way it's all set up and isn't a problem introduced by this change. Maybe we can find a way to clean it up later, but I'm happy to move forward.
