### PR TITLE
Run integration tests on both the CPU and GPU (again)

### LINKED ISSUE #587: Run tests on both the CPU and GPU again
Unit tests should be run on both the CPU and GPU implementations of the "touching" functions to ensure that they both function properly. This was done in #419, but was later reverted.

This is blocked on:
- #576 - without this merged, the touching color test will fail on the CPU.
- #577 - there's currently an "is not touching text bubble" test that will fail on the GPU. Text bubble behavior needs to be ironed out.
- #537 - this isn't necessarily a blocker, but it may be easier to merge #537 and then reimplement CPU/GPU testing than to reapply https://github.com/LLK/scratch-render/pull/419/commits/f9428ee096b7d85f0fe0dc35d6e9ace1c2db59cc and then re-Puppeteer-ify it.

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves #587

### Proposed Changes

This PR adapts the changes in https://github.com/LLK/scratch-render/pull/419/commits/f9428ee096b7d85f0fe0dc35d6e9ace1c2db59cc to the new Playwright-based testing code.

### Reason for Changes

This should increase test coverage and hopefully prevent future bugs that only occur on either the CPU or GPU and as such were not caught by the previous testing behavior.

### Test Coverage

Tests currently fail, which is good because they're catching existing bugs. #576 will need to be merged before tests will pass again. For now, I've disabled the "doesn't touch text bubble" test because there are potential compatibility concerns I want to work out before fixing that (https://github.com/LLK/scratch-render/issues/577).

### CODE REVIEW

File: test/integration/scratch-tests.js [hunk 1]
```diff
@@ -4,55 +4,13 @@ const test = require('tap').test;
...
-                    await new Promise(resolve => setTimeout(resolve, 50));
-                }
-
-                return messages;
-            });
-    });
-
-    // Map string messages to tap reporting methods. This will be used
+const checkOneGpuMode = (t, says) => {
+// Map string messages to tap reporting methods. This will be used
```
Comment (fsih) [inline test/integration/scratch-tests.js]: Indentation?

**Review by cwillisf — APPROVED** [review]
👍 approved pending successful automated tests on CI
