### PR TITLE
Move SVG renderer logic back into SVGSkin

### LINKED ISSUE #550: Subpixel SVG costume handling: a writeup
## The Problem

When editing a vector sprite, weird errors appear. Sometimes, columns/rows appear doubled up, and the very edges of a sprite may get cut off.

jaggies

This becomes particularly noticeable if you're using vector sprites in an animation, and you draw several different frames:

jitter_old

Notice how unstable this appears-- the cat is jittering around, and sometimes the very bottom of its feet get cut off.

## The Root Cause

This is due to a fundamental difference between vector and raster graphics: subpixels.

An SVG costume's `viewBox`, which describes its bounds, can have non-integer dimensions. You can, for instance, have a sprite that's 2.5 pixels wide. However, eventually the sprite will need to be rendered to a texture, and textures necessarily have integer dimensions.

That's not the only problem, however. To further complicate matters, costumes can have non-integer rotation centers. These rotation centers shift a sprite over by a sub-pixel amount. Consider this SVG of a 3x3 circle (viewbox in red):

circle-1

Let's say we rasterize this circle as-is:

circle-1-rasterized

This appears fine. However, the center of this circle is at (1.5, 1.5). This will cause problems if we want to render the circle in the center of a, say, 6x6 stage:

circle-1-rasterized-centered

Now, we need to do some resampling of the already-rasterized SVG! If we do nearest-neighbor resampling, we get the "jaggies" shown earlier. If we do linear resampling, the SVG appears quite blurry. Clearly, we need to take care of this *before* rasterization.

## The Theory

What we need to do is:
1. Shift the SVG so that its rotation center lies on integer coordinates:

circle-1-shift-1 circle-1-shift-2

2. Expand the bounding out to integer coordinates. Note that this step also solves the problem of non-integer `viewBox`es, although it's not shown here:

circle-1-shift-3

3. Adjust the rotation center of the sprite passed to `scratch-render` so that it is relative to the new bounding box. For instance, the above circle's rotation center is now (2, 2).

## The Practice (Attempt 1)

Now comes the implementation. We modify [`SVGRenderer.loadSVG`](https://github.com/LLK/scratch-svg-renderer/blob/ec35ed3ee88869b48a0316263bd083e1364609a9/src/svg-renderer.js#L126) to take the costume's intended rotation center as an argument, and before creating the SVG image, apply the necessary transformations to its `viewBox`. Then, we offset the rotation center used by `scratch-render` by adding it to `SVGRenderer.viewOffset`.

Unfortunately, this doesn't work with mipmaps.

If you render the costume at above 100% size, it works fine, but if you render a mipmap *under* the costume's "native" size, then the rasterized costume may once again have a non-integer size or rotation center--for instance, if you rasterize at half the costume's normal size, you're dividing the rotation center and dimensions by 2.

## The Practice (Attempt 2)

What if we instead applied this bounding-box adjustment each time the costume was rasterized? `SVGSkin` would pass the costume's rotation center to the [`draw` method](https://github.com/LLK/scratch-svg-renderer/blob/ec35ed3ee88869b48a0316263bd083e1364609a9/src/svg-renderer.js#L404) rather than the `loadSVG` method, and in [`_drawFromImage`](https://github.com/LLK/scratch-svg-renderer/blob/ec35ed3ee88869b48a0316263bd083e1364609a9/src/svg-renderer.js#L432), the offsetting and resizing would be applied to the *canvas* that the SVG is being rendered to.

This works fine... in Chrome. But to implement this, you need to call `ctx.drawImage` at non-integer coordinates. And in Firefox, the `drawImage` method [won't render SVGs with the proper subpixel offset, instead resampling them and making them blurry](https://bugzilla.mozilla.org/show_bug.cgi?id=1517901).

So the only cross-browser way to offset an SVG by a subpixel amount is to set its `viewBox`, like we did in our first attempt. But how do we do this without breaking mipmaps?

## The Practice (Attempt 3)

This is mostly the same as attempt 1, but with one key difference: instead of changing the `viewBox` and rotation center to be round numbers, we ensure they are multiples of the smallest mipmap's size.

For instance, if the smallest mipmap is 1/8th the SVG's native scale, we ensure that the `viewBox` and rotation center are multiples of 8. This ensures that, even at the smallest mipmap's size, the SVG is rendered at the proper subpixel position. This is the best cross-browser solution I've found.

## The Demo

I have a rough version of this working in my `subpixel-v2` branches of [`scratch-render`](https://github.com/adroitwhiz/scratch-render/commit/5285b1266bfab60edfe5a29fb931cea55c095d5a) and [`scratch-svg-renderer`](https://github.com/adroitwhiz/scratch-svg-renderer/commit/6f36758a36493480a86af2db6478c3079e4c505f). The code is somewhat old (preceding SVG mipmaps, the removal of `getDrawRatio`, and the synchronous `scratch-svg-renderer` API), but it works well enough to eliminate the jitter and jaggies entirely:

jitter_new

## The Remaining Problem

There's a kink that still needs to be worked out, however. Expanding the viewbox out to multiples of *n* pixels will increase the size of costumes' bounds. This isn't a problem for `getFastBounds` (which doesn't return consistent results and doesn't need to) and `getConvexHullPointsForDrawable` (the size of the convex hull won't be affected at all), but it presents a problem for `getAABB`, which is used (or rather, [should be used](https://github.com/LLK/scratch-render/pull/478)) for fencing sprites.

With the viewbox-expanding behavior in place, there will be a split between a costume's "logical bounds" (aka the `viewBox`), and its "texture bounds" (the dimensions of the quadrilateral rendered by WebGL).

In order to calculate both the "logical bounds" (for fencing behavior) and "texture bounds" (for rendering), it looks to me like `Drawable._calculateTransform` will have to be refactored in some way-- by changing it to calculate both the "logical" and "texture" bounds, by splitting it into two different methods which calculate the two different bounds, or in some other (hopefully less complex) way.

EDIT: Distortion effects will also have to change what they consider the "center" of the sprite.

If you have any ideas for avoiding complexity here, I'd greatly appreciate them.

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

A step towards #550

### Proposed Changes

This PR moves the logic for actually rendering SVGs back into `SVGSkin` from `SvgRenderer`, and removes the dependency on the `SvgRenderer` class.

### Reason for Changes

This will allow for future modifications to the way SVGs are drawn, which are necessary to fix #550.

### Test Coverage

Tested manually

### CODE REVIEW

File: src/SVGSkin.js [hunk 1]
```diff
@@ -94,18 +103,26 @@ class SVGSkin extends Skin {
      * @return {SVGMIP} An object that handles creating and updating SVG textures.
      */
     createMIP (scale) {
-        this._svgRenderer.draw(scale);
+        const {width, height} = this._svgMeasurements;
+        this._canvas.width = width * scale;
+        this._canvas.height = height * scale;
+        // Even if the canvas at the current scale has a nonzero size, the image's dimensions are floored pre-scaling.
+        // e.g. if an image has a width of 0.4 and is being rendered at 3x scale, the canvas will have a width of 1, but
+        // the image's width will be rounded down to 0 on some browsers (Firefox) prior to being drawn at that scale.
```
Comment (adroitwhiz) [inline src/SVGSkin.js]: note to self: move this comment in the middle of the condition so it's clear it refers specifically to the naturalWidth/naturalHeight check

File: src/SVGSkin.js [hunk 2]
```diff
@@ -28,8 +28,17 @@ class SVGSkin extends Skin {
         /** @type {RenderWebGL} */
         this._renderer = renderer;
 
-        /** @type {SvgRenderer} */
-        this._svgRenderer = new SvgRenderer();
+        /** @type {HTMLImageElement} */
+        this._svgImage = null;
+
+        /** @type {Object} */
+        this._svgMeasurements = {x: 0, y: 0, width: 0, height: 0};
```
Comment (adroitwhiz) [inline src/SVGSkin.js]: We don't need x and y right now but will need them for #550

File: src/SVGSkin.js [hunk 3]
```diff
@@ -147,7 +165,7 @@ class SVGSkin extends Skin {
         // Can't use bitwise stuff here because we need to handle negative exponents
         const mipScale = Math.pow(2, mipLevel - INDEX_OFFSET);
 
-        if (this._svgRenderer.loaded && !this._scaledMIPs[mipLevel]) {
+        if (this._svgImage.complete && !this._scaledMIPs[mipLevel]) {
```
Comment (cwillisf) [inline src/SVGSkin.js]: It's not clear to me that this is guaranteed to never become true before the `load` event handler is called. I think to be safe we should set a flag in the `load` event handler and check that here, similar to how the `loaded` flag worked before.

**Review by cwillisf — CHANGES_REQUESTED** [review]
Thanks for doing this, and sorry it took us so long to review it!
There's one small change I've requested just to make sure it's safe but overall it looks pretty good

File: src/SVGSkin.js (hunk 3 above)
Comment (adroitwhiz) [reply src/SVGSkin.js]: I've done so now. This required some additional supporting changes to avoid a race condition in case `setSVG` is called a second time before the original image is finished loading.

**Review by cwillisf — APPROVED** [review]
👍
